from django.urls import path
from .views import (
    DashboardView,
    ProjectBoardView,
    ProjectCreateView,
    IssueCreateView,
    IssueUpdateView,
    MyTasksView,
    update_issue_status, 
    IssueDetailView,
    add_comment,
    add_attachment,
    TeamListView, 
    delete_comment,
    delete_attachment,
    TeamListView,
    ProfileView,
    add_project_attachment,
    DepartmentProjectsView,
    TeamLeadDashboardView,
    BossDashboardView,
    project_delete,
    otp_login_request,
    otp_login_verify,
    InviteUserView,
    NotificationListView,
)

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("my-tasks/", MyTasksView.as_view(), name="my_tasks"), 
    path("projects/new/", ProjectCreateView.as_view(), name="project_create"),
    path("projects/<int:pk>/", ProjectBoardView.as_view(), name="project_board"),
    path(
        "projects/<int:project_id>/issues/new/",
        IssueCreateView.as_view(),
        name="issue_create",
    ),
    path("issues/<int:pk>/", IssueDetailView.as_view(), name="issue_detail"),
    path("issues/<int:pk>/comment/", add_comment, name="issue_add_comment"),
    path("issues/<int:pk>/attach/", add_attachment, name="issue_add_attachment"),
    path("issues/<int:pk>/edit/", IssueUpdateView.as_view(), name="issue_edit"),
    path(
        "issues/<int:pk>/status/",
        update_issue_status,
        name="issue_update_status",
    ),
    path("team/", TeamListView.as_view(), name="team_list"),
    path("comments/<int:pk>/delete/", delete_comment, name="comment_delete"),
    path("attachments/<int:pk>/delete/", delete_attachment, name="attachment_delete"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("projects/<int:pk>/attach/", add_project_attachment, name="project_add_attachment"),
    path(
    "departments/<str:dept_code>/",
    DepartmentProjectsView.as_view(),
    name="department_projects",
    ),
    path("team-lead/", TeamLeadDashboardView.as_view(), name="teamlead_dashboard"),
    path("boss/", BossDashboardView.as_view(), name="boss_dashboard"),
    path("projects/<int:pk>/delete/", project_delete, name="project_delete"),
    path("login/otp/", otp_login_request, name="otp_login"),
    path("login/otp/verify/", otp_login_verify, name="otp_verify"),
    path("members/invite/", InviteUserView.as_view(), name="invite_user"),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
]
