# Generated by Django 5.2.8 on 2025-11-29 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_project_deadline_date_project_issue_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='issue_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
