# Generated by Django 5.2.8 on 2025-11-29 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_issue_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('BOSS', 'Boss'), ('LEAD', 'Team Lead'), ('EMP', 'Employee')], default='EMP', max_length=10)),
                ('department', models.CharField(blank=True, choices=[('DEV', 'Developer'), ('GRAPHIC', 'Graphic'), ('SOCIAL', 'Social Media'), ('AI', 'AI Developer'), ('ELEARN', 'eLearning'), ('LEADGEN', 'Lead')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
