# Generated by Django 5.2.8 on 2025-12-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('DEV', 'Developer'), ('GRAPHIC', 'Graphic'), ('SOCIAL', 'Social Media'), ('AI', 'AI Developer'), ('ELEARNING', 'eLearning'), ('LEAD', 'Lead'), ('SEO', 'SEO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(help_text='Short code, e.g. CRM', max_length=10),
        ),
    ]
