# Generated by Django 5.2.8 on 2025-12-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_profile_department_alter_project_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(blank=True, choices=[('DEV', 'Developer'), ('GRAPHIC', 'Graphic'), ('SOCIAL', 'Social Media'), ('AI', 'AI Developer'), ('ELEARNING', 'eLearning'), ('LEAD', 'Lead'), ('SEO', 'SEO')], max_length=20, null=True),
        ),
    ]
