# Generated by Django 5.2.8 on 2025-12-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_project_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(help_text='Short code, e.g. CRM', max_length=10, unique=True),
        ),
    ]
