# Generated by Django 5.2.8 on 2025-12-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_project_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='show_on_board',
            field=models.BooleanField(default=True, help_text="If false the issue is hidden from the project's kanban columns but still visible in My Tasks and issue detail."),
        ),
    ]
