# Generated by Django 5.2.8 on 2025-12-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.CharField(blank=True, choices=[('DEV', 'Developer'), ('GRAPHIC', 'Graphic'), ('SOCIAL', 'Social Media'), ('AI', 'AI Developer'), ('ELEARNING', 'eLearning'), ('LEAD', 'Lead'), ('SEO', 'SEO')], help_text='Department this project belongs to', max_length=50, null=True),
        ),
    ]
