# Generated by Django 5.2.8 on 2025-12-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reference_url',
            field=models.URLField(blank=True, help_text='Optional: link to docs / design / folder for this project.', null=True),
        ),
    ]
